from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

from .models import KnowledgeIndex
from .taxonomy import describe_module


def _top_level(path: str) -> str:
    return path.split("/", 1)[0]


def export_knowledge_pack(index: KnowledgeIndex, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    module_paths: dict[str, set[str]] = defaultdict(set)
    module_chunk_counts: Counter[str] = Counter()
    tag_counter: Counter[str] = Counter()
    tag_paths: dict[str, list[str]] = defaultdict(list)
    doc_paths: list[str] = []
    for chunk in index.chunks:
        module = _top_level(chunk.path)
        module_paths[module].add(chunk.path)
        module_chunk_counts[module] += 1
        if chunk.kind == "doc" and chunk.path not in doc_paths:
            doc_paths.append(chunk.path)
        for tag in chunk.tags:
            tag_counter[tag] += 1
            if chunk.path not in tag_paths[tag]:
                tag_paths[tag].append(chunk.path)

    lines: list[str] = []
    lines.append("# Mirrorsphere Knowledge Pack")
    lines.append("")
    lines.append("Generated by MirrorHarness for Mirrorsphere platform knowledge Q&A.")
    lines.append("")
    lines.append(f"- Generated at: {index.generated_at}")
    lines.append(f"- Repository root: `{index.repo_root}`")
    lines.append(f"- Source hash: `{index.source_hash}`")
    lines.append(f"- Indexed chunks: {index.chunk_count}")
    lines.append("")
    lines.append("## Module Map")
    lines.append("")
    for module in sorted(module_paths):
        lines.append(f"### {module}")
        lines.append("")
        lines.append(f"- Description: {describe_module(module)}")
        lines.append(f"- Indexed files: {len(module_paths[module])}")
        lines.append(f"- Indexed chunks: {module_chunk_counts[module]}")
        sample_paths = sorted(module_paths[module])[:6]
        lines.append("- Entry files:")
        for path in sample_paths:
            lines.append(f"  - `{path}`")
        lines.append("")

    lines.append("## Capability Index")
    lines.append("")
    for tag, _ in tag_counter.most_common():
        lines.append(f"### {tag}")
        lines.append("")
        for path in tag_paths[tag][:8]:
            lines.append(f"- `{path}`")
        lines.append("")

    lines.append("## Documentation Entry Points")
    lines.append("")
    for path in doc_paths[:20]:
        lines.append(f"- `{path}`")
    lines.append("")

    lines.append("## Investigation Playbook")
    lines.append("")
    lines.append("- Architecture and capability questions: start from `README.md`, `portal/`, and `pilot_web/`.")
    lines.append("- Page or UI questions: trace `pilot_web/src/pages` -> `pilot_web/src/apis` -> `portal/biz/handler` -> `portal/biz/service`.")
    lines.append("- Record / replay / mock / diff questions: connect `recorder/`, `replayer/`, and `portal` service flows instead of treating them as isolated modules.")
    lines.append("- If the answer depends on a concrete implementation point, cite the file path explicitly and distinguish fact from inference.")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path

